/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tetherunit_integrator_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

/* tetherunit_integrator_expl_vde_adj:(i0[13],i1[13],i2,i3[])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=5.3484875186307519e+01;
  a2=2.;
  a3=arg[0]? arg[0][4] : 0;
  a4=arg[0]? arg[0][6] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][3] : 0;
  a7=arg[0]? arg[0][5] : 0;
  a8=(a6*a7);
  a5=(a5+a8);
  a5=(a2*a5);
  a8=(a1*a5);
  a9=arg[0]? arg[0][10] : 0;
  a10=(a8*a9);
  a11=(a7*a4);
  a12=(a6*a3);
  a11=(a11-a12);
  a11=(a2*a11);
  a12=(a1*a11);
  a13=arg[0]? arg[0][11] : 0;
  a14=(a12*a13);
  a10=(a10+a14);
  a14=casadi_sq(a6);
  a15=casadi_sq(a4);
  a14=(a14+a15);
  a14=(a2*a14);
  a15=1.;
  a14=(a14-a15);
  a16=(a1*a14);
  a17=arg[0]? arg[0][12] : 0;
  a18=(a16*a17);
  a10=(a10+a18);
  a18=5.0000000000000000e-01;
  a19=arg[1]? arg[1][6] : 0;
  a20=(a18*a19);
  a21=(a10*a20);
  a22=4.4570729321922942e-01;
  a23=(a3*a7);
  a24=(a6*a4);
  a23=(a23-a24);
  a23=(a2*a23);
  a23=(a22*a23);
  a24=(a23*a9);
  a25=casadi_sq(a6);
  a26=casadi_sq(a7);
  a25=(a25+a26);
  a25=(a2*a25);
  a25=(a25-a15);
  a25=(a22*a25);
  a26=(a25*a13);
  a24=(a24+a26);
  a26=(a7*a4);
  a27=(a6*a3);
  a26=(a26+a27);
  a26=(a2*a26);
  a26=(a22*a26);
  a27=(a26*a17);
  a24=(a24+a27);
  a27=arg[1]? arg[1][5] : 0;
  a28=(a18*a27);
  a29=(a24*a28);
  a21=(a21+a29);
  a29=casadi_sq(a6);
  a30=casadi_sq(a3);
  a29=(a29+a30);
  a29=(a2*a29);
  a29=(a29-a15);
  a29=(a22*a29);
  a30=(a29*a9);
  a31=(a3*a7);
  a32=(a6*a4);
  a31=(a31+a32);
  a31=(a2*a31);
  a31=(a22*a31);
  a32=(a31*a13);
  a30=(a30+a32);
  a32=(a3*a4);
  a33=(a6*a7);
  a32=(a32-a33);
  a32=(a2*a32);
  a32=(a22*a32);
  a33=(a32*a17);
  a30=(a30+a33);
  a33=arg[1]? arg[1][4] : 0;
  a34=(a18*a33);
  a35=(a30*a34);
  a21=(a21+a35);
  a35=(a3*a20);
  a36=(a6*a28);
  a35=(a35+a36);
  a36=(a4*a34);
  a35=(a35-a36);
  a36=arg[1]? arg[1][3] : 0;
  a18=(a18*a36);
  a37=(a7*a18);
  a35=(a35-a37);
  a37=(a17*a35);
  a37=(a22*a37);
  a37=(a2*a37);
  a38=(a3*a37);
  a21=(a21+a38);
  a38=(a6+a6);
  a39=(a13*a35);
  a39=(a22*a39);
  a39=(a2*a39);
  a38=(a38*a39);
  a21=(a21+a38);
  a38=(a9*a35);
  a38=(a22*a38);
  a38=(a2*a38);
  a40=(a4*a38);
  a21=(a21-a40);
  a40=(a4*a28);
  a41=(a7*a20);
  a40=(a40-a41);
  a41=(a6*a34);
  a40=(a40+a41);
  a41=(a3*a18);
  a40=(a40-a41);
  a41=(a17*a40);
  a41=(a22*a41);
  a41=(a2*a41);
  a42=(a7*a41);
  a21=(a21-a42);
  a42=(a13*a40);
  a42=(a22*a42);
  a42=(a2*a42);
  a43=(a4*a42);
  a21=(a21+a43);
  a43=(a6+a6);
  a44=(a9*a40);
  a22=(a22*a44);
  a22=(a2*a22);
  a43=(a43*a22);
  a21=(a21+a43);
  a43=1.0000000000000001e-01;
  a44=casadi_sq(a6);
  a45=casadi_sq(a3);
  a44=(a44+a45);
  a45=casadi_sq(a7);
  a44=(a44+a45);
  a45=casadi_sq(a4);
  a44=(a44+a45);
  a15=(a15-a44);
  a15=(a43*a15);
  a44=(a15*a36);
  a21=(a21+a44);
  a44=(a6+a6);
  a45=(a4*a19);
  a46=(a7*a27);
  a45=(a45+a46);
  a46=(a3*a33);
  a45=(a45+a46);
  a36=(a6*a36);
  a45=(a45+a36);
  a43=(a43*a45);
  a44=(a44*a43);
  a21=(a21-a44);
  a44=(a6+a6);
  a45=arg[0]? arg[0][8] : 0;
  a36=arg[1]? arg[1][10] : 0;
  a46=(a45*a36);
  a47=arg[0]? arg[0][7] : 0;
  a48=arg[1]? arg[1][11] : 0;
  a49=(a47*a48);
  a46=(a46-a49);
  a49=(a6*a20);
  a50=(a3*a28);
  a49=(a49-a50);
  a50=(a7*a34);
  a49=(a49+a50);
  a50=(a4*a18);
  a49=(a49-a50);
  a17=(a17*a49);
  a17=(a1*a17);
  a46=(a46+a17);
  a17=arg[1]? arg[1][2] : 0;
  a46=(a46+a17);
  a46=(a2*a46);
  a44=(a44*a46);
  a21=(a21+a44);
  a44=arg[1]? arg[1][12] : 0;
  a47=(a47*a44);
  a17=arg[0]? arg[0][9] : 0;
  a50=(a17*a36);
  a47=(a47-a50);
  a13=(a13*a49);
  a13=(a1*a13);
  a47=(a47+a13);
  a13=arg[1]? arg[1][1] : 0;
  a47=(a47+a13);
  a47=(a2*a47);
  a13=(a3*a47);
  a21=(a21-a13);
  a17=(a17*a48);
  a45=(a45*a44);
  a17=(a17-a45);
  a9=(a9*a49);
  a1=(a1*a9);
  a17=(a17+a1);
  a1=arg[1]? arg[1][0] : 0;
  a17=(a17+a1);
  a2=(a2*a17);
  a17=(a7*a2);
  a21=(a21+a17);
  if (res[0]!=0) res[0][3]=a21;
  a21=(a24*a20);
  a17=(a10*a28);
  a21=(a21-a17);
  a33=(a15*a33);
  a21=(a21+a33);
  a33=(a6*a37);
  a21=(a21+a33);
  a33=(a7*a38);
  a21=(a21+a33);
  a33=(a30*a18);
  a21=(a21-a33);
  a33=(a4*a41);
  a21=(a21+a33);
  a33=(a7*a42);
  a21=(a21+a33);
  a33=(a3+a3);
  a33=(a33*a22);
  a21=(a21+a33);
  a33=(a3+a3);
  a33=(a33*a43);
  a21=(a21-a33);
  a33=(a6*a47);
  a21=(a21-a33);
  a33=(a4*a2);
  a21=(a21+a33);
  if (res[0]!=0) res[0][4]=a21;
  a27=(a15*a27);
  a20=(a30*a20);
  a27=(a27-a20);
  a20=(a10*a34);
  a27=(a27+a20);
  a20=(a24*a18);
  a27=(a27-a20);
  a20=(a4*a37);
  a27=(a27+a20);
  a20=(a7+a7);
  a20=(a20*a39);
  a27=(a27+a20);
  a20=(a3*a38);
  a27=(a27+a20);
  a20=(a6*a41);
  a27=(a27-a20);
  a20=(a3*a42);
  a27=(a27+a20);
  a20=(a7+a7);
  a20=(a20*a43);
  a27=(a27-a20);
  a20=(a4*a47);
  a27=(a27+a20);
  a20=(a6*a2);
  a27=(a27+a20);
  if (res[0]!=0) res[0][5]=a27;
  a15=(a15*a19);
  a30=(a30*a28);
  a15=(a15+a30);
  a24=(a24*a34);
  a15=(a15-a24);
  a10=(a10*a18);
  a15=(a15-a10);
  a37=(a7*a37);
  a15=(a15+a37);
  a38=(a6*a38);
  a15=(a15-a38);
  a41=(a3*a41);
  a15=(a15+a41);
  a6=(a6*a42);
  a15=(a15+a6);
  a6=(a4+a4);
  a6=(a6*a43);
  a15=(a15-a6);
  a4=(a4+a4);
  a4=(a4*a46);
  a15=(a15+a4);
  a7=(a7*a47);
  a15=(a15+a7);
  a3=(a3*a2);
  a15=(a15+a3);
  if (res[0]!=0) res[0][6]=a15;
  a15=(a11*a44);
  a3=(a14*a48);
  a15=(a15-a3);
  if (res[0]!=0) res[0][7]=a15;
  a14=(a14*a36);
  a44=(a5*a44);
  a14=(a14-a44);
  if (res[0]!=0) res[0][8]=a14;
  a5=(a5*a48);
  a11=(a11*a36);
  a5=(a5-a11);
  if (res[0]!=0) res[0][9]=a5;
  a8=(a8*a49);
  a23=(a23*a35);
  a8=(a8+a23);
  a29=(a29*a40);
  a8=(a8+a29);
  if (res[0]!=0) res[0][10]=a8;
  a12=(a12*a49);
  a25=(a25*a35);
  a12=(a12+a25);
  a31=(a31*a40);
  a12=(a12+a31);
  if (res[0]!=0) res[0][11]=a12;
  a16=(a16*a49);
  a26=(a26*a35);
  a16=(a16+a26);
  a32=(a32*a40);
  a16=(a16+a32);
  if (res[0]!=0) res[0][12]=a16;
  if (res[0]!=0) res[0][13]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tetherunit_integrator_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tetherunit_integrator_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tetherunit_integrator_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void tetherunit_integrator_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tetherunit_integrator_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tetherunit_integrator_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tetherunit_integrator_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tetherunit_integrator_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tetherunit_integrator_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tetherunit_integrator_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tetherunit_integrator_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
