/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tetherunit_integrator_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[95] = {17, 17, 0, 0, 0, 0, 12, 23, 34, 46, 49, 52, 55, 61, 67, 73, 74, 74, 75, 75, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 16, 0, 1, 3, 4, 5, 6, 10, 11, 12, 13, 16, 0, 1, 3, 4, 5, 6, 10, 11, 12, 13, 16, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 16, 11, 12, 16, 10, 12, 16, 10, 11, 16, 3, 4, 5, 6, 13, 16, 3, 4, 5, 6, 13, 16, 3, 4, 5, 6, 13, 16, 13, 13};
static const casadi_int casadi_s4[37] = {17, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s5[4] = {17, 1, 0, 0};
static const casadi_int casadi_s6[3] = {17, 0, 0};

/* tetherunit_integrator_impl_dae_jac_x_xdot_u_z:(i0[17],i1[17],i2,i3[],i4[])->(o0[17x17,75nz],o1[17x17,17nz],o2[17x1,0nz],o3[17x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a8, a9;
  a0=2.;
  a1=arg[0]? arg[0][5] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][0]=a2;
  a3=arg[0]? arg[0][4] : 0;
  a4=(a0*a3);
  a5=(-a4);
  if (res[0]!=0) res[0][1]=a5;
  a5=arg[0]? arg[0][3] : 0;
  a6=(a5+a5);
  a6=(a0*a6);
  if (res[0]!=0) res[0][2]=a6;
  a7=1.0000000000000001e-01;
  a8=1.;
  a9=casadi_sq(a5);
  a10=casadi_sq(a3);
  a9=(a9+a10);
  a10=casadi_sq(a1);
  a9=(a9+a10);
  a10=arg[0]? arg[0][6] : 0;
  a11=casadi_sq(a10);
  a9=(a9+a11);
  a9=(a8-a9);
  a9=(a7*a9);
  a11=(a5+a5);
  a11=(a7*a11);
  a12=(a5*a11);
  a12=(a9-a12);
  a13=5.0000000000000000e-01;
  a14=arg[0]? arg[0][10] : 0;
  a15=4.4570729321922933e+01;
  a16=(a5+a5);
  a16=(a0*a16);
  a17=(a15*a16);
  a17=(a14*a17);
  a18=arg[0]? arg[0][11] : 0;
  a19=(a0*a10);
  a20=(a15*a19);
  a20=(a18*a20);
  a17=(a17+a20);
  a20=arg[0]? arg[0][12] : 0;
  a21=(a0*a1);
  a22=(a15*a21);
  a22=(a20*a22);
  a17=(a17-a22);
  a22=(a3*a17);
  a23=(a5+a5);
  a23=(a0*a23);
  a24=(a15*a23);
  a24=(a18*a24);
  a25=(a0*a10);
  a26=(a15*a25);
  a26=(a14*a26);
  a24=(a24-a26);
  a26=(a0*a3);
  a27=(a15*a26);
  a27=(a20*a27);
  a24=(a24+a27);
  a27=(a1*a24);
  a22=(a22+a27);
  a27=5.3484875186307519e+01;
  a28=(a27*a2);
  a28=(a14*a28);
  a29=(a27*a4);
  a29=(a18*a29);
  a28=(a28-a29);
  a29=(a27*a6);
  a29=(a20*a29);
  a28=(a28+a29);
  a29=(a10*a28);
  a22=(a22+a29);
  a22=(a13*a22);
  a12=(a12-a22);
  if (res[0]!=0) res[0][3]=a12;
  a12=(a5*a17);
  a22=casadi_sq(a5);
  a29=casadi_sq(a3);
  a22=(a22+a29);
  a22=(a0*a22);
  a22=(a22-a8);
  a29=(a15*a22);
  a30=(a29*a14);
  a31=(a3*a1);
  a32=(a5*a10);
  a31=(a31+a32);
  a31=(a0*a31);
  a32=(a15*a31);
  a33=(a32*a18);
  a30=(a30+a33);
  a33=(a3*a10);
  a34=(a5*a1);
  a33=(a33-a34);
  a33=(a0*a33);
  a34=(a15*a33);
  a35=(a34*a20);
  a30=(a30+a35);
  a12=(a12+a30);
  a35=(a1*a28);
  a12=(a12+a35);
  a35=(a10*a24);
  a12=(a12-a35);
  a12=(a13*a12);
  a35=(a3*a11);
  a12=(a12-a35);
  if (res[0]!=0) res[0][4]=a12;
  a12=(a5*a24);
  a35=(a3*a1);
  a36=(a5*a10);
  a35=(a35-a36);
  a35=(a0*a35);
  a36=(a15*a35);
  a37=(a36*a14);
  a38=casadi_sq(a5);
  a39=casadi_sq(a1);
  a38=(a38+a39);
  a38=(a0*a38);
  a38=(a38-a8);
  a39=(a15*a38);
  a40=(a39*a18);
  a37=(a37+a40);
  a40=(a1*a10);
  a41=(a5*a3);
  a40=(a40+a41);
  a40=(a0*a40);
  a41=(a15*a40);
  a42=(a41*a20);
  a37=(a37+a42);
  a12=(a12+a37);
  a42=(a3*a28);
  a12=(a12-a42);
  a42=(a10*a17);
  a12=(a12+a42);
  a12=(a13*a12);
  a42=(a1*a11);
  a12=(a12-a42);
  if (res[0]!=0) res[0][5]=a12;
  a12=(a5*a28);
  a42=(a3*a10);
  a43=(a5*a1);
  a42=(a42+a43);
  a42=(a0*a42);
  a43=(a27*a42);
  a44=(a43*a14);
  a45=(a1*a10);
  a46=(a5*a3);
  a45=(a45-a46);
  a45=(a0*a45);
  a46=(a27*a45);
  a47=(a46*a18);
  a44=(a44+a47);
  a47=casadi_sq(a5);
  a48=casadi_sq(a10);
  a47=(a47+a48);
  a47=(a0*a47);
  a47=(a47-a8);
  a8=(a27*a47);
  a48=(a8*a20);
  a44=(a44+a48);
  a12=(a12+a44);
  a48=(a3*a24);
  a12=(a12+a48);
  a48=(a1*a17);
  a12=(a12-a48);
  a12=(a13*a12);
  a11=(a10*a11);
  a12=(a12-a11);
  if (res[0]!=0) res[0][6]=a12;
  a12=arg[0]? arg[0][9] : 0;
  a11=(a12*a4);
  a48=arg[0]? arg[0][8] : 0;
  a49=(a48*a6);
  a11=(a11+a49);
  if (res[0]!=0) res[0][7]=a11;
  a11=arg[0]? arg[0][7] : 0;
  a6=(a11*a6);
  a49=(a12*a2);
  a6=(a6-a49);
  a6=(-a6);
  if (res[0]!=0) res[0][8]=a6;
  a2=(a48*a2);
  a4=(a11*a4);
  a2=(a2+a4);
  a2=(-a2);
  if (res[0]!=0) res[0][9]=a2;
  a2=arg[0]? arg[0][15] : 0;
  a4=arg[0]? arg[0][13] : 0;
  a6=(a2*a4);
  a49=(a30+a30);
  a50=(a49*a17);
  a51=(a37+a37);
  a52=(a51*a24);
  a50=(a50+a52);
  a52=(a44+a44);
  a53=(a52*a28);
  a50=(a50+a53);
  a53=casadi_sq(a30);
  a54=casadi_sq(a37);
  a53=(a53+a54);
  a54=casadi_sq(a44);
  a53=(a53+a54);
  a53=sqrt(a53);
  a54=(a53+a53);
  a50=(a50/a54);
  a50=(a6*a50);
  a50=(-a50);
  if (res[0]!=0) res[0][10]=a50;
  a50=-4.4570729321922933e+01;
  a55=1.8696874518574300e-02;
  a56=(a55*a37);
  a57=(a56*a44);
  a58=2.2436249422289160e-02;
  a59=(a58*a44);
  a60=(a59*a37);
  a57=(a57-a60);
  a60=(a35*a11);
  a61=(a38*a48);
  a60=(a60+a61);
  a61=(a40*a12);
  a60=(a60+a61);
  a57=(a57-a60);
  a57=(a50*a57);
  a60=(a57+a57);
  a61=(a55*a24);
  a61=(a44*a61);
  a62=(a56*a28);
  a61=(a61+a62);
  a62=(a58*a28);
  a62=(a37*a62);
  a63=(a59*a24);
  a62=(a62+a63);
  a61=(a61-a62);
  a23=(a48*a23);
  a25=(a11*a25);
  a23=(a23-a25);
  a26=(a12*a26);
  a23=(a23+a26);
  a61=(a61-a23);
  a61=(a50*a61);
  a61=(a60*a61);
  a23=(a58*a44);
  a26=(a23*a30);
  a25=(a55*a30);
  a62=(a25*a44);
  a26=(a26-a62);
  a62=(a22*a11);
  a63=(a31*a48);
  a62=(a62+a63);
  a63=(a33*a12);
  a62=(a62+a63);
  a26=(a26+a62);
  a26=(a50*a26);
  a62=(a26+a26);
  a63=(a58*a28);
  a63=(a30*a63);
  a64=(a23*a17);
  a63=(a63+a64);
  a64=(a55*a17);
  a64=(a44*a64);
  a28=(a25*a28);
  a64=(a64+a28);
  a63=(a63-a64);
  a16=(a11*a16);
  a19=(a48*a19);
  a16=(a16+a19);
  a21=(a12*a21);
  a16=(a16-a21);
  a63=(a63+a16);
  a63=(a50*a63);
  a63=(a62*a63);
  a61=(a61+a63);
  a63=-5.3484875186307519e+01;
  a16=(a58*a30);
  a21=(a16*a37);
  a19=(a58*a37);
  a64=(a19*a30);
  a21=(a21-a64);
  a21=(a63*a21);
  a64=(a21+a21);
  a28=(a58*a17);
  a28=(a37*a28);
  a65=(a16*a24);
  a28=(a28+a65);
  a24=(a58*a24);
  a24=(a30*a24);
  a17=(a19*a17);
  a24=(a24+a17);
  a28=(a28-a24);
  a28=(a63*a28);
  a28=(a64*a28);
  a61=(a61+a28);
  a57=casadi_sq(a57);
  a26=casadi_sq(a26);
  a57=(a57+a26);
  a21=casadi_sq(a21);
  a57=(a57+a21);
  a57=sqrt(a57);
  a57=(a57+a57);
  a61=(a61/a57);
  if (res[0]!=0) res[0][11]=a61;
  a61=(a0*a10);
  if (res[0]!=0) res[0][12]=a61;
  a21=(a0*a5);
  a26=(-a21);
  if (res[0]!=0) res[0][13]=a26;
  a26=(a3+a3);
  a26=(a7*a26);
  a28=(a5*a26);
  a24=(a3+a3);
  a24=(a0*a24);
  a17=(a15*a24);
  a17=(a14*a17);
  a65=(a0*a1);
  a66=(a15*a65);
  a66=(a18*a66);
  a17=(a17+a66);
  a66=(a0*a10);
  a67=(a15*a66);
  a67=(a20*a67);
  a17=(a17+a67);
  a67=(a3*a17);
  a67=(a67+a30);
  a68=(a0*a1);
  a69=(a15*a68);
  a69=(a14*a69);
  a70=(a0*a5);
  a71=(a15*a70);
  a71=(a20*a71);
  a69=(a69+a71);
  a71=(a1*a69);
  a67=(a67+a71);
  a71=(a27*a61);
  a71=(a14*a71);
  a72=(a27*a21);
  a72=(a18*a72);
  a71=(a71-a72);
  a72=(a10*a71);
  a67=(a67+a72);
  a67=(a13*a67);
  a28=(a28+a67);
  a28=(-a28);
  if (res[0]!=0) res[0][14]=a28;
  a28=(a5*a17);
  a67=(a1*a71);
  a28=(a28+a67);
  a67=(a10*a69);
  a28=(a28-a67);
  a28=(a13*a28);
  a67=(a3*a26);
  a67=(a9-a67);
  a28=(a28+a67);
  if (res[0]!=0) res[0][15]=a28;
  a28=(a5*a69);
  a67=(a3*a71);
  a67=(a67+a44);
  a28=(a28-a67);
  a67=(a10*a17);
  a28=(a28+a67);
  a28=(a13*a28);
  a67=(a1*a26);
  a28=(a28-a67);
  if (res[0]!=0) res[0][16]=a28;
  a28=(a5*a71);
  a67=(a3*a69);
  a67=(a67+a37);
  a28=(a28+a67);
  a67=(a1*a17);
  a28=(a28-a67);
  a28=(a13*a28);
  a26=(a10*a26);
  a28=(a28-a26);
  if (res[0]!=0) res[0][17]=a28;
  a28=(a12*a21);
  if (res[0]!=0) res[0][18]=a28;
  a28=(a12*a61);
  if (res[0]!=0) res[0][19]=a28;
  a61=(a48*a61);
  a21=(a11*a21);
  a61=(a61+a21);
  a61=(-a61);
  if (res[0]!=0) res[0][20]=a61;
  a61=(a49*a17);
  a21=(a51*a69);
  a61=(a61+a21);
  a21=(a52*a71);
  a61=(a61+a21);
  a61=(a61/a54);
  a61=(a6*a61);
  a61=(-a61);
  if (res[0]!=0) res[0][21]=a61;
  a61=(a55*a69);
  a61=(a44*a61);
  a21=(a56*a71);
  a61=(a61+a21);
  a21=(a58*a71);
  a21=(a37*a21);
  a28=(a59*a69);
  a21=(a21+a28);
  a61=(a61-a21);
  a68=(a11*a68);
  a70=(a12*a70);
  a68=(a68+a70);
  a61=(a61-a68);
  a61=(a50*a61);
  a61=(a60*a61);
  a68=(a58*a71);
  a68=(a30*a68);
  a70=(a23*a17);
  a68=(a68+a70);
  a70=(a55*a17);
  a70=(a44*a70);
  a71=(a25*a71);
  a70=(a70+a71);
  a68=(a68-a70);
  a24=(a11*a24);
  a65=(a48*a65);
  a24=(a24+a65);
  a66=(a12*a66);
  a24=(a24+a66);
  a68=(a68+a24);
  a68=(a50*a68);
  a68=(a62*a68);
  a61=(a61+a68);
  a68=(a58*a17);
  a68=(a37*a68);
  a24=(a16*a69);
  a68=(a68+a24);
  a69=(a58*a69);
  a69=(a30*a69);
  a17=(a19*a17);
  a69=(a69+a17);
  a68=(a68-a69);
  a68=(a63*a68);
  a68=(a64*a68);
  a61=(a61+a68);
  a61=(a61/a57);
  if (res[0]!=0) res[0][22]=a61;
  a61=(a0*a5);
  if (res[0]!=0) res[0][23]=a61;
  a68=(a0*a10);
  if (res[0]!=0) res[0][24]=a68;
  a69=(a1+a1);
  a69=(a7*a69);
  a17=(a5*a69);
  a24=(a0*a3);
  a66=(a15*a24);
  a66=(a18*a66);
  a65=(a0*a5);
  a70=(a15*a65);
  a70=(a20*a70);
  a66=(a66-a70);
  a70=(a3*a66);
  a71=(a0*a3);
  a21=(a15*a71);
  a21=(a14*a21);
  a28=(a1+a1);
  a28=(a0*a28);
  a26=(a15*a28);
  a26=(a18*a26);
  a21=(a21+a26);
  a26=(a0*a10);
  a67=(a15*a26);
  a67=(a20*a67);
  a21=(a21+a67);
  a67=(a1*a21);
  a67=(a67+a37);
  a70=(a70+a67);
  a67=(a27*a61);
  a67=(a14*a67);
  a72=(a27*a68);
  a72=(a18*a72);
  a67=(a67+a72);
  a72=(a10*a67);
  a70=(a70+a72);
  a70=(a13*a70);
  a17=(a17+a70);
  a17=(-a17);
  if (res[0]!=0) res[0][25]=a17;
  a17=(a5*a66);
  a70=(a1*a67);
  a70=(a70+a44);
  a17=(a17+a70);
  a70=(a10*a21);
  a17=(a17-a70);
  a17=(a13*a17);
  a70=(a3*a69);
  a17=(a17-a70);
  if (res[0]!=0) res[0][26]=a17;
  a17=(a5*a21);
  a70=(a3*a67);
  a17=(a17-a70);
  a70=(a10*a66);
  a17=(a17+a70);
  a17=(a13*a17);
  a70=(a1*a69);
  a70=(a9-a70);
  a17=(a17+a70);
  if (res[0]!=0) res[0][27]=a17;
  a17=(a5*a67);
  a70=(a3*a21);
  a17=(a17+a70);
  a70=(a1*a66);
  a70=(a70+a30);
  a17=(a17-a70);
  a17=(a13*a17);
  a69=(a10*a69);
  a17=(a17-a69);
  if (res[0]!=0) res[0][28]=a17;
  a17=(a12*a68);
  a17=(-a17);
  if (res[0]!=0) res[0][29]=a17;
  a17=(a12*a61);
  if (res[0]!=0) res[0][30]=a17;
  a61=(a48*a61);
  a68=(a11*a68);
  a61=(a61-a68);
  a61=(-a61);
  if (res[0]!=0) res[0][31]=a61;
  a61=(a49*a66);
  a68=(a51*a21);
  a61=(a61+a68);
  a68=(a52*a67);
  a61=(a61+a68);
  a61=(a61/a54);
  a61=(a6*a61);
  a61=(-a61);
  if (res[0]!=0) res[0][32]=a61;
  a61=(a55*a21);
  a61=(a44*a61);
  a68=(a56*a67);
  a61=(a61+a68);
  a68=(a58*a67);
  a68=(a37*a68);
  a17=(a59*a21);
  a68=(a68+a17);
  a61=(a61-a68);
  a71=(a11*a71);
  a28=(a48*a28);
  a71=(a71+a28);
  a26=(a12*a26);
  a71=(a71+a26);
  a61=(a61-a71);
  a61=(a50*a61);
  a61=(a60*a61);
  a71=(a58*a67);
  a71=(a30*a71);
  a26=(a23*a66);
  a71=(a71+a26);
  a26=(a55*a66);
  a26=(a44*a26);
  a67=(a25*a67);
  a26=(a26+a67);
  a71=(a71-a26);
  a24=(a48*a24);
  a65=(a12*a65);
  a24=(a24-a65);
  a71=(a71+a24);
  a71=(a50*a71);
  a71=(a62*a71);
  a61=(a61+a71);
  a71=(a58*a66);
  a71=(a37*a71);
  a24=(a16*a21);
  a71=(a71+a24);
  a21=(a58*a21);
  a21=(a30*a21);
  a66=(a19*a66);
  a21=(a21+a66);
  a71=(a71-a21);
  a71=(a63*a71);
  a71=(a64*a71);
  a61=(a61+a71);
  a61=(a61/a57);
  if (res[0]!=0) res[0][33]=a61;
  a61=(a0*a3);
  if (res[0]!=0) res[0][34]=a61;
  a71=(a0*a1);
  if (res[0]!=0) res[0][35]=a71;
  a21=(a10+a10);
  a21=(a0*a21);
  if (res[0]!=0) res[0][36]=a21;
  a66=(a10+a10);
  a7=(a7*a66);
  a66=(a5*a7);
  a24=(a0*a5);
  a65=(a15*a24);
  a65=(a18*a65);
  a26=(a0*a3);
  a67=(a15*a26);
  a67=(a20*a67);
  a65=(a65+a67);
  a67=(a3*a65);
  a28=(a0*a1);
  a68=(a15*a28);
  a68=(a20*a68);
  a0=(a0*a5);
  a15=(a15*a0);
  a15=(a14*a15);
  a68=(a68-a15);
  a15=(a1*a68);
  a67=(a67+a15);
  a15=(a27*a61);
  a14=(a14*a15);
  a15=(a27*a71);
  a18=(a18*a15);
  a14=(a14+a18);
  a27=(a27*a21);
  a20=(a20*a27);
  a14=(a14+a20);
  a20=(a10*a14);
  a20=(a20+a44);
  a67=(a67+a20);
  a67=(a13*a67);
  a66=(a66+a67);
  a66=(-a66);
  if (res[0]!=0) res[0][37]=a66;
  a66=(a5*a65);
  a67=(a1*a14);
  a66=(a66+a67);
  a67=(a10*a68);
  a67=(a67+a37);
  a66=(a66-a67);
  a66=(a13*a66);
  a67=(a3*a7);
  a66=(a66-a67);
  if (res[0]!=0) res[0][38]=a66;
  a66=(a5*a68);
  a67=(a3*a14);
  a66=(a66-a67);
  a67=(a10*a65);
  a67=(a67+a30);
  a66=(a66+a67);
  a66=(a13*a66);
  a67=(a1*a7);
  a66=(a66-a67);
  if (res[0]!=0) res[0][39]=a66;
  a66=(a5*a14);
  a67=(a3*a68);
  a66=(a66+a67);
  a67=(a1*a65);
  a66=(a66-a67);
  a66=(a13*a66);
  a7=(a10*a7);
  a9=(a9-a7);
  a66=(a66+a9);
  if (res[0]!=0) res[0][40]=a66;
  a66=(a12*a71);
  a9=(a48*a21);
  a66=(a66-a9);
  a66=(-a66);
  if (res[0]!=0) res[0][41]=a66;
  a21=(a11*a21);
  a66=(a12*a61);
  a21=(a21-a66);
  a21=(-a21);
  if (res[0]!=0) res[0][42]=a21;
  a61=(a48*a61);
  a71=(a11*a71);
  a61=(a61-a71);
  a61=(-a61);
  if (res[0]!=0) res[0][43]=a61;
  a61=(a49*a65);
  a71=(a51*a68);
  a61=(a61+a71);
  a71=(a52*a14);
  a61=(a61+a71);
  a61=(a61/a54);
  a61=(a6*a61);
  a61=(-a61);
  if (res[0]!=0) res[0][44]=a61;
  a61=(a55*a68);
  a61=(a44*a61);
  a71=(a56*a14);
  a61=(a61+a71);
  a71=(a58*a14);
  a71=(a37*a71);
  a21=(a59*a68);
  a71=(a71+a21);
  a61=(a61-a71);
  a28=(a12*a28);
  a11=(a11*a0);
  a28=(a28-a11);
  a61=(a61-a28);
  a61=(a50*a61);
  a61=(a60*a61);
  a28=(a58*a14);
  a28=(a30*a28);
  a11=(a23*a65);
  a28=(a28+a11);
  a11=(a55*a65);
  a11=(a44*a11);
  a14=(a25*a14);
  a11=(a11+a14);
  a28=(a28-a11);
  a48=(a48*a24);
  a12=(a12*a26);
  a48=(a48+a12);
  a28=(a28+a48);
  a28=(a50*a28);
  a28=(a62*a28);
  a61=(a61+a28);
  a28=(a58*a65);
  a28=(a37*a28);
  a48=(a16*a68);
  a28=(a28+a48);
  a68=(a58*a68);
  a68=(a30*a68);
  a65=(a19*a65);
  a68=(a68+a65);
  a28=(a28-a68);
  a28=(a63*a28);
  a28=(a64*a28);
  a61=(a61+a28);
  a61=(a61/a57);
  if (res[0]!=0) res[0][45]=a61;
  a61=(-a47);
  if (res[0]!=0) res[0][46]=a61;
  if (res[0]!=0) res[0][47]=a45;
  a22=(a50*a22);
  a22=(a62*a22);
  a35=(a50*a35);
  a35=(a60*a35);
  a22=(a22-a35);
  a22=(a22/a57);
  if (res[0]!=0) res[0][48]=a22;
  if (res[0]!=0) res[0][49]=a47;
  a47=(-a42);
  if (res[0]!=0) res[0][50]=a47;
  a31=(a50*a31);
  a31=(a62*a31);
  a38=(a50*a38);
  a38=(a60*a38);
  a31=(a31-a38);
  a31=(a31/a57);
  if (res[0]!=0) res[0][51]=a31;
  a45=(-a45);
  if (res[0]!=0) res[0][52]=a45;
  if (res[0]!=0) res[0][53]=a42;
  a33=(a50*a33);
  a33=(a62*a33);
  a40=(a50*a40);
  a40=(a60*a40);
  a33=(a33-a40);
  a33=(a33/a57);
  if (res[0]!=0) res[0][54]=a33;
  a33=(a3*a29);
  a40=(a1*a36);
  a33=(a33+a40);
  a40=(a10*a43);
  a33=(a33+a40);
  a33=(a13*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][55]=a33;
  a33=(a5*a29);
  a40=(a1*a43);
  a33=(a33+a40);
  a40=(a10*a36);
  a33=(a33-a40);
  a33=(a13*a33);
  if (res[0]!=0) res[0][56]=a33;
  a33=(a5*a36);
  a40=(a3*a43);
  a33=(a33-a40);
  a40=(a10*a29);
  a33=(a33+a40);
  a33=(a13*a33);
  if (res[0]!=0) res[0][57]=a33;
  a33=(a5*a43);
  a40=(a3*a36);
  a33=(a33+a40);
  a40=(a1*a29);
  a33=(a33-a40);
  a33=(a13*a33);
  if (res[0]!=0) res[0][58]=a33;
  a33=(a49*a29);
  a40=(a51*a36);
  a33=(a33+a40);
  a40=(a52*a43);
  a33=(a33+a40);
  a33=(a33/a54);
  a33=(a6*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][59]=a33;
  a33=(a55*a36);
  a33=(a44*a33);
  a40=(a56*a43);
  a33=(a33+a40);
  a40=(a58*a43);
  a40=(a37*a40);
  a42=(a59*a36);
  a40=(a40+a42);
  a33=(a33-a40);
  a33=(a50*a33);
  a33=(a60*a33);
  a40=(a58*a43);
  a40=(a30*a40);
  a42=(a23*a29);
  a40=(a40+a42);
  a42=(a55*a29);
  a42=(a44*a42);
  a43=(a25*a43);
  a42=(a42+a43);
  a40=(a40-a42);
  a40=(a50*a40);
  a40=(a62*a40);
  a33=(a33+a40);
  a40=(a58*a29);
  a40=(a37*a40);
  a42=(a16*a36);
  a40=(a40+a42);
  a36=(a58*a36);
  a36=(a30*a36);
  a29=(a19*a29);
  a36=(a36+a29);
  a40=(a40-a36);
  a40=(a63*a40);
  a40=(a64*a40);
  a33=(a33+a40);
  a33=(a33/a57);
  if (res[0]!=0) res[0][60]=a33;
  a33=(a3*a32);
  a40=(a1*a39);
  a33=(a33+a40);
  a40=(a10*a46);
  a33=(a33+a40);
  a33=(a13*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][61]=a33;
  a33=(a5*a32);
  a40=(a1*a46);
  a33=(a33+a40);
  a40=(a10*a39);
  a33=(a33-a40);
  a33=(a13*a33);
  if (res[0]!=0) res[0][62]=a33;
  a33=(a5*a39);
  a40=(a3*a46);
  a33=(a33-a40);
  a40=(a10*a32);
  a33=(a33+a40);
  a33=(a13*a33);
  if (res[0]!=0) res[0][63]=a33;
  a33=(a5*a46);
  a40=(a3*a39);
  a33=(a33+a40);
  a40=(a1*a32);
  a33=(a33-a40);
  a33=(a13*a33);
  if (res[0]!=0) res[0][64]=a33;
  a33=(a49*a32);
  a40=(a51*a39);
  a33=(a33+a40);
  a40=(a52*a46);
  a33=(a33+a40);
  a33=(a33/a54);
  a33=(a6*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][65]=a33;
  a33=(a55*a39);
  a33=(a44*a33);
  a40=(a56*a46);
  a33=(a33+a40);
  a40=(a58*a46);
  a40=(a37*a40);
  a36=(a59*a39);
  a40=(a40+a36);
  a33=(a33-a40);
  a33=(a50*a33);
  a33=(a60*a33);
  a40=(a58*a46);
  a40=(a30*a40);
  a36=(a23*a32);
  a40=(a40+a36);
  a36=(a55*a32);
  a36=(a44*a36);
  a46=(a25*a46);
  a36=(a36+a46);
  a40=(a40-a36);
  a40=(a50*a40);
  a40=(a62*a40);
  a33=(a33+a40);
  a40=(a58*a32);
  a40=(a37*a40);
  a36=(a16*a39);
  a40=(a40+a36);
  a39=(a58*a39);
  a39=(a30*a39);
  a32=(a19*a32);
  a39=(a39+a32);
  a40=(a40-a39);
  a40=(a63*a40);
  a40=(a64*a40);
  a33=(a33+a40);
  a33=(a33/a57);
  if (res[0]!=0) res[0][66]=a33;
  a33=(a3*a34);
  a40=(a1*a41);
  a33=(a33+a40);
  a40=(a10*a8);
  a33=(a33+a40);
  a33=(a13*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][67]=a33;
  a33=(a5*a34);
  a40=(a1*a8);
  a33=(a33+a40);
  a40=(a10*a41);
  a33=(a33-a40);
  a33=(a13*a33);
  if (res[0]!=0) res[0][68]=a33;
  a33=(a5*a41);
  a40=(a3*a8);
  a33=(a33-a40);
  a10=(a10*a34);
  a33=(a33+a10);
  a33=(a13*a33);
  if (res[0]!=0) res[0][69]=a33;
  a5=(a5*a8);
  a3=(a3*a41);
  a5=(a5+a3);
  a1=(a1*a34);
  a5=(a5-a1);
  a13=(a13*a5);
  if (res[0]!=0) res[0][70]=a13;
  a49=(a49*a34);
  a51=(a51*a41);
  a49=(a49+a51);
  a52=(a52*a8);
  a49=(a49+a52);
  a49=(a49/a54);
  a6=(a6*a49);
  a6=(-a6);
  if (res[0]!=0) res[0][71]=a6;
  a6=(a55*a41);
  a6=(a44*a6);
  a56=(a56*a8);
  a6=(a6+a56);
  a56=(a58*a8);
  a56=(a37*a56);
  a59=(a59*a41);
  a56=(a56+a59);
  a6=(a6-a56);
  a6=(a50*a6);
  a60=(a60*a6);
  a6=(a58*a8);
  a6=(a30*a6);
  a23=(a23*a34);
  a6=(a6+a23);
  a55=(a55*a34);
  a44=(a44*a55);
  a25=(a25*a8);
  a44=(a44+a25);
  a6=(a6-a44);
  a50=(a50*a6);
  a62=(a62*a50);
  a60=(a60+a62);
  a62=(a58*a34);
  a37=(a37*a62);
  a16=(a16*a41);
  a37=(a37+a16);
  a58=(a58*a41);
  a30=(a30*a58);
  a19=(a19*a34);
  a30=(a30+a19);
  a37=(a37-a30);
  a63=(a63*a37);
  a64=(a64*a63);
  a60=(a60+a64);
  a60=(a60/a57);
  if (res[0]!=0) res[0][72]=a60;
  a2=(a53*a2);
  a2=(-a2);
  if (res[0]!=0) res[0][73]=a2;
  a53=(a53*a4);
  a53=(-a53);
  if (res[0]!=0) res[0][74]=a53;
  a53=-1.;
  if (res[1]!=0) res[1][0]=a53;
  if (res[1]!=0) res[1][1]=a53;
  if (res[1]!=0) res[1][2]=a53;
  if (res[1]!=0) res[1][3]=a53;
  if (res[1]!=0) res[1][4]=a53;
  if (res[1]!=0) res[1][5]=a53;
  if (res[1]!=0) res[1][6]=a53;
  if (res[1]!=0) res[1][7]=a53;
  if (res[1]!=0) res[1][8]=a53;
  if (res[1]!=0) res[1][9]=a53;
  if (res[1]!=0) res[1][10]=a53;
  if (res[1]!=0) res[1][11]=a53;
  if (res[1]!=0) res[1][12]=a53;
  if (res[1]!=0) res[1][13]=a53;
  if (res[1]!=0) res[1][14]=a53;
  if (res[1]!=0) res[1][15]=a53;
  if (res[1]!=0) res[1][16]=a53;
  return 0;
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tetherunit_integrator_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tetherunit_integrator_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tetherunit_integrator_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void tetherunit_integrator_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tetherunit_integrator_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int tetherunit_integrator_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real tetherunit_integrator_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tetherunit_integrator_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tetherunit_integrator_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tetherunit_integrator_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tetherunit_integrator_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tetherunit_integrator_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
